sudo: required
dist: trusty
language: java
jobs:
  include:    
    - name: oap-mllib
      dist: bionic
      jdk:
      - openjdk8
      before_install:
      - echo ${TRAVIS_COMMIT_MESSAGE}
      - echo "Installing oneAPI ..."
      - cd /tmp
      - wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
      - sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
      - rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
      - echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
      - sudo apt-get update
      - sudo apt-get install intel-oneapi-daal-devel intel-oneapi-tbb-devel
      - echo "Building oneCCL ..."
      - cd /tmp
      - git clone https://github.com/oneapi-src/oneCCL
      - cd oneCCL && mkdir build && cd build
      - cmake ..
      - make install
      install:
      - # Download spark 3.0
      - "[ -f spark ] || mkdir spark && cd spark && wget http://archive.apache.org/dist/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz && cd .."
      - "tar -xf ./spark/spark-3.0.0-bin-hadoop2.7.tgz"
      - "export SPARK_HOME=`pwd`/spark-3.0.0-bin-hadoop2.7"  
      before_script:
      script:  
      - cd ${TRAVIS_BUILD_DIR}/oap-mllib/mllib-dal
      - source /opt/intel/inteloneapi/setvars.sh
      - source /tmp/oneCCL/build/_install/env/setvars.sh
      - ./build.sh
